### ISSUE TITLE
Get images from Firebase when deployed on web

### ISSUE THREAD

**Issue by T-Davis** [T-Davis/secret_seal_sauce#32]
When deployed images from Firebase are not rendering. This may be CORS-related.

**Comment by nickmeinhold** [comment]
@T-Davis which images are we talking about?  When I go to the latest preview: https://secret-seal-sauce--pr33-update-firebase-vggxntdf.web.app I get: 

<img width="1053" alt="Screen Shot 2021-05-11 at 1 25 44 pm" src="https://user-images.githubusercontent.com/1059276/117753819-784d4f80-b25c-11eb-9827-2931512e5776.png">

**Comment by T-Davis** [comment]
@nickmeinhold, good question! I left that description pretty vague. 

The steps that will get you to the gallery_page are:
Click 'Find A Seal' in the top right corner
Then, click any link (blue text) on the next page

**Comment by nickmeinhold** [comment]
Nice! Looks like CORS to me - apparently you can [configure the bucket](https://firebase.google.com/docs/storage/web/download-files#cors_configuration).

@T-Davis are you happy to do this?  I'm not sure if I have access...

**Comment by T-Davis** [comment]
@nickmeinhold I'm happy to, and thanks for the link!
I think you do have [access](https://console.firebase.google.com/u/0/project/secret-seal-sauce/overview) though 😉

**Comment by nickmeinhold** [comment]
I believe this was fixed by #36

**Comment by nickmeinhold** [comment]
Great work btw @T-Davis... particularly in avoiding the potential rabbit hole of CORS questions! 🙂
